;WITH EMP_DETAIL AS (
SELECT
	EmpID,EmpName,Salary,HIREDATE,DEPARTMENT,
	ROW_NUMBER() OVER (PARTITION BY DEPARTMENT ORDER BY HIREDATE) AS RANK
FROM Employees)
SELECT 
	*
FROM EMP_DETAIL WHERE RANK = 1