-- @ShipOfLearning
-- Find Total winning Percentage of Team
SELECT * FROM Matches
; WITH TOTAL_MATCHES AS (
SELECT Team1 AS TEAM
FROM Matches
UNION ALL 
SELECT Team2 AS TEAM
FROM Matches),
MATCH_COUNT AS 
(
SELECT TEAM, COUNT(*) MC
FROM TOTAL_MATCHES
GROUP BY TEAM),
WINS AS (
SELECT  Winner, COUNT(*) TW
FROM Matches
GROUP BY Winner
)
SELECT 
	M.TEAM, M.MC TOTAL_MATCH_PLAYED,
	(W.TW * 100)/M.MC AS WINNING_PER
FROM MATCH_COUNT M
LEFT JOIN WINS W
ON M.TEAM = W.Winner
ORDER BY WINNING_PER DESC

