SELECT * FROM Products
SELECT * FROM Prices

;WITH PRD AS (SELECT 
	ProductName, ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS RN
FROM Products),
PRS AS (
SELECT 
	Price, ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS RN
FROM Prices)

SELECT ProductName,Price
FROM 
PRD INNER JOIN PRS
ON PRD.RN = PRS.RN