-- @ShipOfLearning
-- Windows Funcaiton Sum(), AVG(),Count(), Min(), Max()

SELECT * FROM Employees
SELECT * FROM SalesTransactions

;WITH CTE AS (
SELECT
	EmpName,Department,Salary,HireDate,
	SUM(Salary) OVER (PARTITION BY DEPARTMENT) AS TOTAL,
	AVG(Salary) OVER (PARTITION BY DEPARTMENT) AS AVGDEPART,
	COUNT(Salary) OVER (PARTITION BY DEPARTMENT) AS HEADCOUNT,
	MIN(Salary) OVER (PARTITION BY DEPARTMENT) AS MINSALARY,
	MAX(Salary) OVER (PARTITION BY DEPARTMENT) AS MAXSALARY
FROM Employees
)
SELECT * FROM CTE WHERE
SALARY < AVGDEPART
