-- Handle Null value with
--	1. Ternary funcation
--	2. Case When
--	3. ISNULL()
--	4. COALESCE()
--	SELECT * FROM EMPLOYEES

SELECT
	EmpID,EmpName,
	--Ternary funcation
	IIF(SALARY IS NULL,BONUS,SALARY) AS SALARY_TERNARY,
	-- CASE WHEN
	CASE WHEN SALARY IS NULL THEN BONUS ELSE SALARY END AS SALARY_CASE,
	--ISNULL
	ISNULL(SALARY,BONUS) AS SALARY_ISNULL,
	--COALESCE()
	COALESCE(Salary,BONUS,0) AS SALARY_COALESCE,
	Bonus
FROM Employees