--SELECT * FROM Employees

DECLARE @N AS INT  = 6;

--SUB QUERY
SELECT * FROM Employees WHERE SALARY = (
SELECT DISTINCT SALARY FROM Employees ORDER BY SALARY DESC
OFFSET (@N-1) ROWS
FETCH NEXT 1 ROWS ONLY)

--DENSE_RANK
; WITH TEMPSALARY AS 
(
SELECT EmpName,Salary, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RN FROM Employees
)
SELECT * FROM TEMPSALARY WHERE RN = @N

----ROW_NUMBER
; WITH TEMPSALARY AS 
(
SELECT EmpName,Salary, ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS RN FROM Employees
)
SELECT * FROM TEMPSALARY WHERE RN = @N