-- FIND 2 HIGEST SALARY EMPLOYEE FROM EACH DEPARTMENT

;WITH EMP_DETAILS AS (
SELECT
	EmpName,Salary,Department,
	DENSE_RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANK
FROM Employees)
SELECT
	EmpName,Salary,Department,RANK
FROM EMP_DETAILS
WHERE RANK < 3
ORDER BY RANK