--SELECT * FROM Employees
SELECT EmpID,EmpName,Salary,
ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS RN
FROM Employees

SELECT EmpID,EmpName,Salary,
RANK() OVER(ORDER BY SALARY DESC) AS RN
FROM Employees

SELECT EmpID,EmpName,Salary,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RN
FROM Employees
